spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 
    
amazonProperties:
  endpointUrl: https://s3.ap-northeast-1.amazonaws.com
  accessKey: xxxxx
  secretKey: xxxxx
  bucketName: nghi-upload-image